### ISSUE TITLE
Value: Block blobs are

### ISSUE THREAD

**Issue by sjuliper7** [matthewbdaly/laravel-azure-storage#7] opened 2019-03-30 13:42 UTC
MicrosoftAzure\Storage\Common\Exceptions\ServiceException: Fail:↵Code: 400↵Value: Block blobs are

I have read the documentation, i'm student junior programmer i'have configure as the documentation but when put image to disk have some error.

```
Storage::disk('azure')->put($fileName,$image);
$path = Storage::url($fileName);
```

**Comment by matthewbdaly** [comment] 2019-03-30 19:07
That error message sounds incomplete. Is there more?

The fact that it raises a 400 error implies the issue is a client error. Maybe have a look at https://stackoverflow.com/questions/45805403/azure-blob-storage-400-bad-request

**Comment by matthewbdaly** [comment] 2019-04-08 13:50
Is this resolved? If so, please let me know and I'll close it.

**Closed as completed** 2019-04-10 01:47 UTC
